### ISSUE TITLE
AIOBEs in examples.Demo with Java 8u74

### ISSUE THREAD

**Issue by hb91546** [JanKoehnlein/FXDiagram#43]
Introduction and Summary Nodes open and close without Exceptions.

Other Nodes experience repeated AIOBEs.
I note a fix for https://bugs.openjdk.java.net/browse/JDK-8096304

Does this trace look familiar?

de.fxdiagram.core.XConnection layoutChildren
SEVERE: ArrayIndexOutOfBoundsException in XConnection.layoutChildren() -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.sun.javafx.collections.ObservableListWrapper.get(Unknown Source)
	at com.sun.javafx.collections.VetoableListDecorator.get(Unknown Source)
	at javafx.scene.Parent.updateCachedBounds(Unknown Source)
	at javafx.scene.Parent.recomputeBounds(Unknown Source)
... elided
	at javafx.scene.Node$LazyBoundsProperty.get(Unknown Source)
	at javafx.scene.Node.getBoundsInLocal(Unknown Source)
	at de.fxdiagram.core.anchors.ConnectionRouter.midPoint(ConnectionRouter.java:593)
	at de.fxdiagram.core.anchors.ConnectionRouter.findClosestSourceAnchor(ConnectionRouter.java:548)
	at de.fxdiagram.core.anchors.ConnectionRouter.calculatePoints(ConnectionRouter.java:318)
	at de.fxdiagram.core.XConnection.layoutChildren(XConnection.java:679)

**Comment by hb91546** [comment]
runconfig pointed to wrong JRE
