### ISSUE TITLE
[eclipse] Save diagram to SVG causes NPE

### ISSUE THREAD

**Issue by ralfellner** [JanKoehnlein/FXDiagram#45]
I'm using version 0.25.0-SNAPSHOT of FXDiagram with Eclipse. I get the following error when saving a diagram as SVG:

`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at de.fxdiagram.core.export.SvgExporter.doGetSvgLink(SvgExporter.java:640)
	at de.fxdiagram.core.export.SvgExporter.toSvgElement(SvgExporter.java:168)
	at de.fxdiagram.core.export.SvgExporter.toSvg(SvgExporter.java:136)
	at de.fxdiagram.core.export.SvgExporter.toSvg(SvgExporter.java:162)
	at de.fxdiagram.core.tools.actions.ExportSvgAction.perform(ExportSvgAction.java:61)
	at de.fxdiagram.core.tools.DiagramActionTool.lambda$11(DiagramActionTool.java:192)` 

`linkProvider` is set to null when using method `def toSvg(XDiagram diagram, File baseDir)`. I think there should be a null check in `def SvgLink doGetSvgLink(Node node)`, e.g.:

`val newLink = linkProvider?.getLink(node) ?: SvgLink.NONE`

**Comment by JanKoehnlein** [comment]
Fixed in 0.26.0
