### ISSUE TITLE
Oomph setup issues

### ISSUE THREAD

**Issue by kthoms** [JanKoehnlein/FXDiagram#54]
I am setting up the devenv with the current Oomph setup. The result has some issues, some of them discussable. I would expect after executing the setup a fully initialized workspace with the projects organized into their working sets and without build errors.

***Modular Target***
The Target Platform fails to be set. Seems that the FX Diagram repo must be part of the target.
```
Performing Targlets Modular Target (FXDiagram), activate
Repository http://download.eclipse.org/releases/luna
Repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Repository http://download.eclipse.org/efxclipse/runtime-released/2.4.0/site
Repository http://download.eclipse.org/efxclipse/updates-released/2.4.0/site
Repository http://meysholdt.github.io/xtext_examples/repositories/generated-with-xtext_2_8_4/
Offline = true
Mirrors = true
Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Adding repository http://download.eclipse.org/releases/luna
Adding repository http://download.eclipse.org/efxclipse/updates-released/2.4.0/site
Adding repository http://meysholdt.github.io/xtext_examples/repositories/generated-with-xtext_2_8_4/
Adding repository http://download.eclipse.org/efxclipse/runtime-released/2.4.0/site
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:778)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1128)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1036)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3305)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3248)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4469)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4463)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4461)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3239)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3214)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3114)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1482228551439
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: FXDiagram Eclipse Integration 0.32.0.v20161220-110905 (de.fxdiagram.eclipse 0.32.0.v20161220-110905) requires 'bundle org.eclipse.ui.ide 3.11.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1482228551439
    ERROR: org.eclipse.equinox.p2.director code=0 To: de.fxdiagram.sdk.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: FXDiagram SDK 0.32.0.v20161220-110905 (de.fxdiagram.sdk.feature.feature.group 0.32.0.v20161220-110905)
    ERROR: org.eclipse.equinox.p2.director code=0 To: de.fxdiagram.eclipse 0.0.0
```

***Project Import***
The setup does contain project import tasks.

***Setup redirect***
In order to be able to edit the materialized setup a setup description usually contains a redirection system property in an Eclipse Ini task.

**Comment by kthoms** [comment]
```
Missing requirement: FXDiagram Eclipse Integration 0.32.0.v20161220-110905 (de.fxdiagram.eclipse 0.32.0.v20161220-110905) requires 'bundle org.eclipse.ui.ide 3.11.0' 
but it could not be found
```

Version 3.11 and higher  of o.e.ui.ide is not available in Luna, but from Mars on. 

The actual problem was that I selected default as target platform in the Oomph wizard, which was Luna. The setup works when Mars is selected.

So either Luna has to be dropped from the supported targets, or the requirements should be lowered. I think latter should be possible.

**Comment by kthoms** [comment]
The requirement is defined in `de.fxdiagram.eclipse`:
```
 org.eclipse.ui.ide;bundle-version="3.11.0"
```
Could this be lowered to 3.10.0 (Luna)?
